### ISSUE TITLE
VNFD page sometimes does not show content

### ISSUE THREAD

**Issue by gc4rella** [openbaton/dashboard#32]
see attached screenshot 

![screenshot 2016-12-02 16 20 27](https://cloud.githubusercontent.com/assets/4677363/20839050/57d3cebe-b8ab-11e6-9d7a-1688c260b22b.png)

On the browser console I can see this error message: 

:8080/js/libs/angular/angular.js:12389 TypeError: Cannot set property 'id' of null
    at HTMLDocument.<anonymous> (http://localhost:8080/js/controllers/nsdController.js:936:28)
    at c (http://localhost:8080/js/libs/jquery/jquery.min.js:4:26036)
    at Object.add [as done] (http://localhost:8080/js/libs/jquery/jquery.min.js:4:26346)
    at init.ready (http://localhost:8080/js/libs/jquery/jquery.min.js:4:2058)
    at new <anonymous> (http://localhost:8080/js/controllers/nsdController.js:933:31)
    at invoke (http://localhost:8080/js/libs/angular/angular.js:4499:27)
    at Object.instantiate (http://localhost:8080/js/libs/angular/angular.js:4507:37)
    at http://localhost:8080/js/libs/angular/angular.js:9074:38
    at link (http://localhost:8080/js/libs/angular/angular-route.min.js:7:208)
    at invokeLinkFn (http://localhost:8080/js/libs/angular/angular.js:8709:25) <div ng-view="" class="ng-scope">

**Comment by gc4rella** [comment]
It seems 3.0.1 solves this issue.
